---

- name: set nginx configuration file
  template:
    src: nginx.conf.j2
    dest: '{{ nginx_path }}/nginx.conf'
    owner: root
    group: root
    mode: 0644
  notify: nginx_restart

- name: set nginx snippets
  copy:
    src: '{{ item }}'
    dest: '{{ nginx_path}}/{{ item }}'
    owner: root
    group: root
    mode: 0644
  notify: nginx_restart
  with_items: '{{ nginx_snippets }}'